services:
  - type: web
    name: a2a-agent-hub
    env: python
    region: oregon
    plan: free
    branch: main
    pythonVersion: 3.8.19
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PORT
        value: 8080
